=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 1.82.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Synctera::ApplicationsBetaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApplicationsBetaApi' do
  before do
    # run before each test
    @api_instance = Synctera::ApplicationsBetaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationsBetaApi' do
    it 'should create an instance of ApplicationsBetaApi' do
      expect(@api_instance).to be_instance_of(Synctera::ApplicationsBetaApi)
    end
  end

  # unit tests for create_application
  # Create an application
  # &gt; 🚧 Beta &gt; This is an Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Submit a record of application details for an account. 
  # @param application Application model.
  # @param [Hash] opts the optional parameters
  # @return [ApplicationResponse]
  describe 'create_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_application
  # Get an application
  # &gt; 🚧 Beta &gt; This is an Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Get an application&#39;s details. 
  # @param application_id Unique identifier for the application.
  # @param [Hash] opts the optional parameters
  # @return [ApplicationResponse]
  describe 'get_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_applications
  # List applications
  # &gt; 🚧 Beta &gt; This is an Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  List records of applications made for accounts. 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :customer_id A list of customer unique identifiers, with a comma separating any values.
  # @option opts [ApplicationType] :type Type of application 
  # @option opts [String] :page_token 
  # @option opts [Integer] :limit 
  # @option opts [Array<String>] :sort_by Specifies the sort order for the returned applications. 
  # @option opts [AllApplicationStatus] :status Application status values for all types of applications 
  # @option opts [Array<String>] :business_id A list of business unique identifiers, with a comma separating any values. Returns applications that are linked to the specified Business IDs.
  # @return [ApplicationList]
  describe 'list_applications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_application
  # Modify an application
  # &gt; 🚧 Beta &gt; This is an Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Modify an existing application for an account. 
  # @param application_id Unique identifier for the application.
  # @param application_patch Application fields to be patched.
  # @param [Hash] opts the optional parameters
  # @return [ApplicationResponse]
  describe 'patch_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
