=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 1.82.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Synctera::BulkIssuanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BulkIssuanceApi' do
  before do
    # run before each test
    @api_instance = Synctera::BulkIssuanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BulkIssuanceApi' do
    it 'should create an instance of BulkIssuanceApi' do
      expect(@api_instance).to be_instance_of(Synctera::BulkIssuanceApi)
    end
  end

  # unit tests for create_bulk_order_config
  # Create a bulk order configuration
  # Bulk card orders can be configured to ship cards in bulk.  In order to create a bulk order the associated card product needs to be configured for bulk issuance (Refer to Card Product &#x60;bulk_shipping_enabled&#x60;).  Once a Card Product is configured a bulk order can be created.   Cards are dynamically added to the bulk order using the &#x60;bulk_order_config_id&#x60; (Refer to Issue Card &#x60;bulk_order_config_id&#x60;)  and will be shipped based on the &#x60;bulk_issuance_policy&#x60;.   Bulk orders configured with &#x60;AUTO&#x60; will be fulfilled daily at 9:30PM PST, all cards that have been added to the bulk order prior to the cutoff  will be shipped in the next bulk order, any subsequent cards will be added to the next days order. Bulk orders configured with &#x60;MANUAL&#x60;  will be shipped when an integrator sends a fulfillment request (Refer to Bulk Issuance Fulfill). 
  # @param bulk_issuance_request Bulk issuance configuration
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key An idempotency key is an arbitrary unique value generated by client to detect subsequent retries of the same request. It is recommended that a UUID or a similar random identifier be used as an idempotency key. A different key must be used for each request, unless it is a retry.
  # @return [BulkIssuanceResponse]
  describe 'create_bulk_order_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for fulfill_bulk_order
  # Fulfill a bulk order
  # Bulk orders configured with a &#x60;MANUAL&#x60; bulk issuance policy will be shipped when a fulfillment request is made (Refer to Bulk Orders &#x60;bulk_issuance_policy&#x60;).  All cards that have been created with the corresponding &#x60;bulk_order_config_id&#x60; since the previous fulfillment, will be included in the bulk order. 
  # @param bulk_order_config_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key An idempotency key is an arbitrary unique value generated by client to detect subsequent retries of the same request. It is recommended that a UUID or a similar random identifier be used as an idempotency key. A different key must be used for each request, unless it is a retry.
  # @return [nil]
  describe 'fulfill_bulk_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_bulk_order_config
  # Get bulk order configuration
  # Get the details about a bulk order configuration. 
  # @param bulk_order_config_id 
  # @param [Hash] opts the optional parameters
  # @return [BulkIssuanceResponse]
  describe 'get_bulk_order_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_bulk_order_configs
  # List Bulk Order Configurations
  # List bulk order configurations matching query parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token 
  # @option opts [String] :card_product_id 
  # @option opts [Array<String>] :sort_by Specifies the sort order for the returned bulk order configurations. 
  # @option opts [Integer] :limit 
  # @return [BulkIssuanceListResponse]
  describe 'list_bulk_order_configs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
