=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 1.82.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Synctera::CardTransactionSimulationsBetaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CardTransactionSimulationsBetaApi' do
  before do
    # run before each test
    @api_instance = Synctera::CardTransactionSimulationsBetaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CardTransactionSimulationsBetaApi' do
    it 'should create an instance of CardTransactionSimulationsBetaApi' do
      expect(@api_instance).to be_instance_of(Synctera::CardTransactionSimulationsBetaApi)
    end
  end

  # unit tests for simulate_authorization
  # Simulate authorization
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Simulate an &#x60;authorization&#x60; type transaction by including the &#x60;card_token&#x60; and other authorization details in your request. 
  # @param [Hash] opts the optional parameters
  # @option opts [AuthRequestModel] :auth_request_model Authorization details
  # @return [Object]
  describe 'simulate_authorization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_authorization_advice
  # Simulate authorization advice
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  An authorization advice allows an amount to be decreased after the authorization. This endpoint allows you to simulate post-swipe adjustments.  Simulate an &#x60;authorization.advice&#x60; type transaction by including the &#x60;original_transaction_token&#x60; and other authorization details in your request. 
  # @param [Hash] opts the optional parameters
  # @option opts [AuthorizationAdviceModel] :authorization_advice_model Authorization advice details
  # @return [Object]
  describe 'simulate_authorization_advice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_balance_inquiry
  # Simulate balance inquiry
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Simulate a &#x60;pindebit.balanceinquiry&#x60; type transaction by sending a POST request to the &#x60;/simulate/financial/balanceinquiry&#x60; endpoint. 
  # @param balance_inquiry_request_model Balance inquiry details
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'simulate_balance_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_clearing
  # Simulate clearing or refund
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Simulate an &#x60;authorization.clearing&#x60; type transaction by including the &#x60;original_transaction_token&#x60; and &#x60;amount&#x60; in your request. To simulate a refund type transaction, set the &#x60;is_refund&#x60; field to true. 
  # @param [Hash] opts the optional parameters
  # @option opts [ClearingModel] :clearing_model Transaction clearing or refund details
  # @return [Object]
  describe 'simulate_clearing test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_financial
  # Simulate financial
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  A \&quot;financial\&quot; is a transaction message class that includes ATM transactions, PIN-debit transactions, and balance inquiries.  Simulate a &#x60;pindebit&#x60; type transaction by including the &#x60;card_token&#x60; and &#x60;amount&#x60; in your request. 
  # @param financial_request_model Financial details
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'simulate_financial test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_financial_advice
  # Simulate financial advice
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Simulate a financial advice by including the &#x60;original_transaction_token&#x60; and other authorization details in JSON format in the body of the request. 
  # @param authorization_advice_model Financial advice details
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'simulate_financial_advice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_original_credit
  # Simulate OCT
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  This Original Credit Transaction (OCT) enables the cardholder to receive funds on the specified card from an external source via the card network. Use this endpoint to simulate a transaction that is similar to a wire transfer and not linked to any purchase.  Simulate an OCT by including the &#x60;card_token&#x60;, &#x60;amount&#x60;, &#x60;mid&#x60;, and &#x60;type&#x60; in your request. 
  # @param original_credit_request_model OCT details
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'simulate_original_credit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_reversal
  # Simulate reversal
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  A reversal releases the hold that was placed on account funds by an authorization, thus returning the funds to the account.  Simulate an &#x60;authorization.reversal&#x60; type transaction by including the &#x60;original_transaction_token&#x60; and &#x60;amount&#x60; in your request. 
  # @param reversal_model Reversal details
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'simulate_reversal test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for simulate_withdrawal
  # Simulate ATM withdrawal
  # &gt; 🚧 Beta &gt; This is a Beta endpoint. Feedback from the community is welcome. We may make breaking changes to this endpoint.  Simulate a &#x60;pindebit.atm.withdrawal&#x60; type transaction by including the &#x60;card_token&#x60; and &#x60;amount&#x60; in your request. 
  # @param withdrawal_request_model ATM withdrawal details
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'simulate_withdrawal test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
