=begin
#Synctera API

#<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.74.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Synctera::TransactionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TransactionsApi' do
  before do
    # run before each test
    @api_instance = Synctera::TransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionsApi' do
    it 'should create an instance of TransactionsApi' do
      expect(@api_instance).to be_instance_of(Synctera::TransactionsApi)
    end
  end

  # unit tests for get_pending_transaction_by_id
  # Get a pending transaction
  # Get a pending transaction by its uuid 
  # @param id Transaction ID
  # @param [Hash] opts the optional parameters
  # @return [PendingTransaction]
  describe 'get_pending_transaction_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_posted_transaction_by_id
  # Get a posted transaction
  # Get a posted transaction by its uuid 
  # @param id Transaction ID
  # @param [Hash] opts the optional parameters
  # @return [PostedTransaction]
  describe 'get_posted_transaction_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pending_transactions
  # List pending transactions
  # Get paginated list of pending transactions matching the provided filters 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_child_transactions Include transactions from sub-accounts when listing transactions for a given account
  # @option opts [Date] :from_date Only display transactions with a posting date greater than from_date
  # @option opts [Date] :to_date Only display transactions with a posting date less than or equal to to_date
  # @option opts [String] :transaction_id Only display holds linked to the provided transaction id
  # @option opts [Array<String>] :status The status of the transaction
  # @option opts [String] :type Only display transactions matching the given type
  # @option opts [Array<String>] :idempotency_key Transaction Idempotency Key(s). Multiple keys can be provided as a comma-separated list.
  # @option opts [String] :account_no Account number
  # @option opts [Boolean] :exclude_jit_transactions Hide \&quot;JIT funding\&quot; transactions from results
  # @option opts [String] :page_token 
  # @option opts [String] :account_id Account ID
  # @option opts [String] :card_id Card ID
  # @option opts [String] :reference_id Reference ID
  # @option opts [Integer] :limit 
  # @option opts [String] :subtype Only display transactions matching the given subtype
  # @return [PendingTransactions]
  describe 'list_pending_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_posted_transactions
  # List posted transactions
  # Get paginated list of posted transactions matching the provided filters 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_child_transactions Include transactions from sub-accounts when listing transactions for a given account
  # @option opts [Array<String>] :uuid Transaction UUID(s). Multiple UUIDs can be provided as a comma-separated list.
  # @option opts [Date] :from_date Only display transactions with a posting date greater than from_date
  # @option opts [Date] :to_date Only display transactions with a posting date less than or equal to to_date
  # @option opts [String] :type Only display transactions matching the given type
  # @option opts [Array<String>] :idempotency_key Transaction Idempotency Key(s). Multiple keys can be provided as a comma-separated list.
  # @option opts [String] :account_no Account number
  # @option opts [Boolean] :exclude_jit_transactions Hide \&quot;JIT funding\&quot; transactions from results
  # @option opts [String] :page_token 
  # @option opts [String] :account_id Account ID
  # @option opts [String] :card_id Card ID
  # @option opts [String] :reference_id Reference ID
  # @option opts [Integer] :limit 
  # @option opts [String] :subtype Only display transactions matching the given subtype
  # @return [PostedTransactions]
  describe 'list_posted_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
