=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 1.82.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Synctera::SyncteraPayDirection
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Synctera::SyncteraPayDirection do
  let(:instance) { Synctera::SyncteraPayDirection.new }

  describe 'test an instance of SyncteraPayDirection' do
    it 'should create an instance of SyncteraPayDirection' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Synctera::SyncteraPayDirection)
    end
  end

end
