=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.139.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Synctera
  class AccountRelationshipType
    ACCOUNT_HOLDER = "ACCOUNT_HOLDER".freeze
    AUTHORIZED_SIGNER = "AUTHORIZED_SIGNER".freeze
    AUTHORIZED_USER = "AUTHORIZED_USER".freeze
    JOINT_ACCOUNT_HOLDER = "JOINT_ACCOUNT_HOLDER".freeze
    PRIMARY_ACCOUNT_HOLDER = "PRIMARY_ACCOUNT_HOLDER".freeze

    def self.all_vars
      @all_vars ||= [ACCOUNT_HOLDER, AUTHORIZED_SIGNER, AUTHORIZED_USER, JOINT_ACCOUNT_HOLDER, PRIMARY_ACCOUNT_HOLDER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AccountRelationshipType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AccountRelationshipType"
    end
  end
end
