=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.108.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module Synctera
  class AddAccountsRequest
    attr_accessor :account_identifiers

    # The names of the account owners.
    attr_accessor :account_owner_names

    # The identifier for the business customer associated with this external account. Exactly one of `business_id` or `customer_id` must be specified. 
    attr_accessor :business_id

    # ISO 4217 alphabetic currency code
    attr_accessor :currency

    # The identifier for the personal customer associated with this external account. Exactly one of `customer_id` or `business_id` must be specified. 
    attr_accessor :customer_id

    attr_accessor :customer_type

    # User-supplied metadata
    attr_accessor :metadata

    # A user-meaningful name for the account
    attr_accessor :nickname

    attr_accessor :routing_identifiers

    # The type of the account
    attr_accessor :type

    # The ID of the vendor account, will be empty for MANUAL vendor
    attr_accessor :vendor_account_id

    attr_accessor :verification

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_identifiers' => :'account_identifiers',
        :'account_owner_names' => :'account_owner_names',
        :'business_id' => :'business_id',
        :'currency' => :'currency',
        :'customer_id' => :'customer_id',
        :'customer_type' => :'customer_type',
        :'metadata' => :'metadata',
        :'nickname' => :'nickname',
        :'routing_identifiers' => :'routing_identifiers',
        :'type' => :'type',
        :'vendor_account_id' => :'vendor_account_id',
        :'verification' => :'verification'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_identifiers' => :'AddAccountsRequestAccountIdentifiers',
        :'account_owner_names' => :'Array<String>',
        :'business_id' => :'String',
        :'currency' => :'String',
        :'customer_id' => :'String',
        :'customer_type' => :'ExtAccountCustomerType',
        :'metadata' => :'Object',
        :'nickname' => :'String',
        :'routing_identifiers' => :'AddAccountsRequestRoutingIdentifiers',
        :'type' => :'String',
        :'vendor_account_id' => :'String',
        :'verification' => :'AccountVerification'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'verification'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Synctera::AddAccountsRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Synctera::AddAccountsRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_identifiers')
        self.account_identifiers = attributes[:'account_identifiers']
      else
        self.account_identifiers = nil
      end

      if attributes.key?(:'account_owner_names')
        if (value = attributes[:'account_owner_names']).is_a?(Array)
          self.account_owner_names = value
        end
      else
        self.account_owner_names = nil
      end

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'customer_type')
        self.customer_type = attributes[:'customer_type']
      else
        self.customer_type = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'nickname')
        self.nickname = attributes[:'nickname']
      end

      if attributes.key?(:'routing_identifiers')
        self.routing_identifiers = attributes[:'routing_identifiers']
      else
        self.routing_identifiers = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'vendor_account_id')
        self.vendor_account_id = attributes[:'vendor_account_id']
      end

      if attributes.key?(:'verification')
        self.verification = attributes[:'verification']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_identifiers.nil?
        invalid_properties.push('invalid value for "account_identifiers", account_identifiers cannot be nil.')
      end

      if @account_owner_names.nil?
        invalid_properties.push('invalid value for "account_owner_names", account_owner_names cannot be nil.')
      end

      if @account_owner_names.length < 1
        invalid_properties.push('invalid value for "account_owner_names", number of items must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if !@currency.nil? && @currency !~ pattern
        invalid_properties.push("invalid value for \"currency\", must conform to the pattern #{pattern}.")
      end

      if @customer_type.nil?
        invalid_properties.push('invalid value for "customer_type", customer_type cannot be nil.')
      end

      if !@nickname.nil? && @nickname.to_s.length < 1
        invalid_properties.push('invalid value for "nickname", the character length must be great than or equal to 1.')
      end

      if @routing_identifiers.nil?
        invalid_properties.push('invalid value for "routing_identifiers", routing_identifiers cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if !@vendor_account_id.nil? && @vendor_account_id.to_s.length < 1
        invalid_properties.push('invalid value for "vendor_account_id", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_identifiers.nil?
      return false if @account_owner_names.nil?
      return false if @account_owner_names.length < 1
      return false if !@currency.nil? && @currency !~ Regexp.new(/^[A-Z]{3}$/)
      return false if @customer_type.nil?
      return false if !@nickname.nil? && @nickname.to_s.length < 1
      return false if @routing_identifiers.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["CHECKING", "SAVINGS"])
      return false unless type_validator.valid?(@type)
      return false if !@vendor_account_id.nil? && @vendor_account_id.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_owner_names Value to be assigned
    def account_owner_names=(account_owner_names)
      if account_owner_names.nil?
        fail ArgumentError, 'account_owner_names cannot be nil'
      end

      if account_owner_names.length < 1
        fail ArgumentError, 'invalid value for "account_owner_names", number of items must be greater than or equal to 1.'
      end

      @account_owner_names = account_owner_names
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if currency !~ pattern
        fail ArgumentError, "invalid value for \"currency\", must conform to the pattern #{pattern}."
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] nickname Value to be assigned
    def nickname=(nickname)
      if nickname.nil?
        fail ArgumentError, 'nickname cannot be nil'
      end

      if nickname.to_s.length < 1
        fail ArgumentError, 'invalid value for "nickname", the character length must be great than or equal to 1.'
      end

      @nickname = nickname
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["CHECKING", "SAVINGS"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] vendor_account_id Value to be assigned
    def vendor_account_id=(vendor_account_id)
      if vendor_account_id.nil?
        fail ArgumentError, 'vendor_account_id cannot be nil'
      end

      if vendor_account_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "vendor_account_id", the character length must be great than or equal to 1.'
      end

      @vendor_account_id = vendor_account_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_identifiers == o.account_identifiers &&
          account_owner_names == o.account_owner_names &&
          business_id == o.business_id &&
          currency == o.currency &&
          customer_id == o.customer_id &&
          customer_type == o.customer_type &&
          metadata == o.metadata &&
          nickname == o.nickname &&
          routing_identifiers == o.routing_identifiers &&
          type == o.type &&
          vendor_account_id == o.vendor_account_id &&
          verification == o.verification
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_identifiers, account_owner_names, business_id, currency, customer_id, customer_type, metadata, nickname, routing_identifiers, type, vendor_account_id, verification].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Synctera.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
