=begin
#Synctera API

#<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.74.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module Synctera
  # A period of time in which a customer is (was) employed by a particular employer. 
  class Employment
    # Name of customer's employer.
    attr_accessor :employer_name

    # First day of employment.
    attr_accessor :employment_from

    # Number of hours spent per week working for specified employment.
    attr_accessor :employment_hours

    # Annual income in cents.
    attr_accessor :employment_income

    # The 3-letter alphabetic ISO 4217 code for the currency in which the employee was paid. 
    attr_accessor :employment_income_currency

    # A collection of arbitrary key-value pairs providing additional information about this employment relationship. 
    attr_accessor :employment_info

    # Customer's work title, profession, or field.
    attr_accessor :employment_occupation

    # Last day of employment.
    attr_accessor :employment_to

    # Unique ID for this employment relationship.
    attr_accessor :id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'employer_name' => :'employer_name',
        :'employment_from' => :'employment_from',
        :'employment_hours' => :'employment_hours',
        :'employment_income' => :'employment_income',
        :'employment_income_currency' => :'employment_income_currency',
        :'employment_info' => :'employment_info',
        :'employment_occupation' => :'employment_occupation',
        :'employment_to' => :'employment_to',
        :'id' => :'id'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'employer_name' => :'String',
        :'employment_from' => :'Time',
        :'employment_hours' => :'Float',
        :'employment_income' => :'Integer',
        :'employment_income_currency' => :'String',
        :'employment_info' => :'Object',
        :'employment_occupation' => :'String',
        :'employment_to' => :'Time',
        :'id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Synctera::Employment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Synctera::Employment`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'employer_name')
        self.employer_name = attributes[:'employer_name']
      else
        self.employer_name = nil
      end

      if attributes.key?(:'employment_from')
        self.employment_from = attributes[:'employment_from']
      end

      if attributes.key?(:'employment_hours')
        self.employment_hours = attributes[:'employment_hours']
      end

      if attributes.key?(:'employment_income')
        self.employment_income = attributes[:'employment_income']
      end

      if attributes.key?(:'employment_income_currency')
        self.employment_income_currency = attributes[:'employment_income_currency']
      end

      if attributes.key?(:'employment_info')
        self.employment_info = attributes[:'employment_info']
      end

      if attributes.key?(:'employment_occupation')
        self.employment_occupation = attributes[:'employment_occupation']
      end

      if attributes.key?(:'employment_to')
        self.employment_to = attributes[:'employment_to']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @employer_name.nil?
        invalid_properties.push('invalid value for "employer_name", employer_name cannot be nil.')
      end

      if !@employment_hours.nil? && @employment_hours > 80
        invalid_properties.push('invalid value for "employment_hours", must be smaller than or equal to 80.')
      end

      if !@employment_hours.nil? && @employment_hours < 0
        invalid_properties.push('invalid value for "employment_hours", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @employer_name.nil?
      return false if !@employment_hours.nil? && @employment_hours > 80
      return false if !@employment_hours.nil? && @employment_hours < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] employment_hours Value to be assigned
    def employment_hours=(employment_hours)
      if employment_hours.nil?
        fail ArgumentError, 'employment_hours cannot be nil'
      end

      if employment_hours > 80
        fail ArgumentError, 'invalid value for "employment_hours", must be smaller than or equal to 80.'
      end

      if employment_hours < 0
        fail ArgumentError, 'invalid value for "employment_hours", must be greater than or equal to 0.'
      end

      @employment_hours = employment_hours
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          employer_name == o.employer_name &&
          employment_from == o.employment_from &&
          employment_hours == o.employment_hours &&
          employment_income == o.employment_income &&
          employment_income_currency == o.employment_income_currency &&
          employment_info == o.employment_info &&
          employment_occupation == o.employment_occupation &&
          employment_to == o.employment_to &&
          id == o.id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [employer_name, employment_from, employment_hours, employment_income, employment_income_currency, employment_info, employment_occupation, employment_to, id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Synctera.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
