=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.139.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Synctera
  class EventTypeWildcard
    ACCOUNT = "ACCOUNT.*".freeze
    ACH = "ACH.*".freeze
    APPLICATION = "APPLICATION.*".freeze
    BUSINESS = "BUSINESS.*".freeze
    CARD = "CARD.*".freeze
    CASE = "CASE.*".freeze
    CASH_PICKUP = "CASH_PICKUP.*".freeze
    CREDIT_SCORE = "CREDIT_SCORE.*".freeze
    CUSTOMER = "CUSTOMER.*".freeze
    EXTERNAL_CARD = "EXTERNAL_CARD.*".freeze
    EXTERNAL_CARD_TRANSFER = "EXTERNAL_CARD_TRANSFER.*".freeze
    INTEREST = "INTEREST.*".freeze
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER.*".freeze
    NOTE = "NOTE.*".freeze
    PAYMENT_SCHEDULE = "PAYMENT_SCHEDULE.*".freeze
    PERSON = "PERSON.*".freeze
    STATEMENT = "STATEMENT.*".freeze
    TRANSACTION = "TRANSACTION.*".freeze

    def self.all_vars
      @all_vars ||= [ACCOUNT, ACH, APPLICATION, BUSINESS, CARD, CASE, CASH_PICKUP, CREDIT_SCORE, CUSTOMER, EXTERNAL_CARD, EXTERNAL_CARD_TRANSFER, INTEREST, INTERNAL_TRANSFER, NOTE, PAYMENT_SCHEDULE, PERSON, STATEMENT, TRANSACTION].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventTypeWildcard.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventTypeWildcard"
    end
  end
end
