=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.108.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module Synctera
  class Frequency
    BI_WEEKLY = "BI_WEEKLY".freeze
    DAILY = "DAILY".freeze
    MONTHLY = "MONTHLY".freeze
    ONE_TIME = "ONE_TIME".freeze
    OTHER = "OTHER".freeze
    QUARTERLY = "QUARTERLY".freeze
    SEMI_MONTHLY = "SEMI_MONTHLY".freeze
    WEEKLY = "WEEKLY".freeze
    YEARLY = "YEARLY".freeze

    def self.all_vars
      @all_vars ||= [BI_WEEKLY, DAILY, MONTHLY, ONE_TIME, OTHER, QUARTERLY, SEMI_MONTHLY, WEEKLY, YEARLY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Frequency.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Frequency"
    end
  end
end
