=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.145.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Synctera
  # Send an ACH
  class OutgoingAchRequest
    # Amount to transfer in ISO 4217 minor currency units
    attr_accessor :amount

    # Company Entry Description field in ACH batch header. Originator inserts this field's value to provide the Receiver with a description of the entry's purpose.
    attr_accessor :company_entry_description

    # Overrides the 'Company Name' field in ACH batch header, which otherwise defaults to the configured partner name. The provided name will be prepended with the Bank's configured prefix and a *. It will then be truncated to 16 characters.
    attr_accessor :company_name

    # ISO 4217 alphabetic currency code of the transfer amount
    attr_accessor :currency

    # The customer's unique identifier
    attr_accessor :customer_id

    # The type of transaction (debit or credit). A debit is a transfer in and a credit is a transfer out of the originating account
    attr_accessor :dc_sign

    # Effective date transaction proccesses (is_same_day needs to be false or not present at all)
    attr_accessor :effective_date

    # Additional transfer metadata structured as key-value pairs
    attr_accessor :external_data

    # ID of the international customer that receives the final remittance transfer (required for OFAC enabled payments)
    attr_accessor :final_customer_id

    attr_accessor :hold

    # Send as same day ACH transaction (use only is_same_day without specific effective_date)
    attr_accessor :is_same_day

    # Memo for the payment
    attr_accessor :memo

    # The unique identifier for an originating account
    attr_accessor :originating_account_id

    # The unique identifier for an receiving account
    attr_accessor :receiving_account_id

    # Will be sent to the ACH network and maps to Addenda record 05 - the recipient bank will receive this info
    attr_accessor :reference_info

    attr_accessor :risk

    # Standard Entry Class Code: * WEB: Internet initiated / Mobile Entry (default if empty) * CCD: Corporate Credit or Debit * PPD: Pre-arranged Payment or Deposit (only deposits currently supported)
    attr_accessor :sec_code

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'company_entry_description' => :'company_entry_description',
        :'company_name' => :'company_name',
        :'currency' => :'currency',
        :'customer_id' => :'customer_id',
        :'dc_sign' => :'dc_sign',
        :'effective_date' => :'effective_date',
        :'external_data' => :'external_data',
        :'final_customer_id' => :'final_customer_id',
        :'hold' => :'hold',
        :'is_same_day' => :'is_same_day',
        :'memo' => :'memo',
        :'originating_account_id' => :'originating_account_id',
        :'receiving_account_id' => :'receiving_account_id',
        :'reference_info' => :'reference_info',
        :'risk' => :'risk',
        :'sec_code' => :'sec_code'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'Integer',
        :'company_entry_description' => :'String',
        :'company_name' => :'String',
        :'currency' => :'String',
        :'customer_id' => :'String',
        :'dc_sign' => :'String',
        :'effective_date' => :'Date',
        :'external_data' => :'Object',
        :'final_customer_id' => :'String',
        :'hold' => :'AchRequestHoldData',
        :'is_same_day' => :'Boolean',
        :'memo' => :'String',
        :'originating_account_id' => :'String',
        :'receiving_account_id' => :'String',
        :'reference_info' => :'String',
        :'risk' => :'RiskData',
        :'sec_code' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'company_entry_description',
        :'effective_date',
        :'external_data',
        :'final_customer_id',
        :'hold',
        :'is_same_day',
        :'memo',
        :'reference_info',
        :'risk',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Synctera::OutgoingAchRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Synctera::OutgoingAchRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'company_entry_description')
        self.company_entry_description = attributes[:'company_entry_description']
      end

      if attributes.key?(:'company_name')
        self.company_name = attributes[:'company_name']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      else
        self.customer_id = nil
      end

      if attributes.key?(:'dc_sign')
        self.dc_sign = attributes[:'dc_sign']
      else
        self.dc_sign = nil
      end

      if attributes.key?(:'effective_date')
        self.effective_date = attributes[:'effective_date']
      end

      if attributes.key?(:'external_data')
        self.external_data = attributes[:'external_data']
      end

      if attributes.key?(:'final_customer_id')
        self.final_customer_id = attributes[:'final_customer_id']
      end

      if attributes.key?(:'hold')
        self.hold = attributes[:'hold']
      end

      if attributes.key?(:'is_same_day')
        self.is_same_day = attributes[:'is_same_day']
      end

      if attributes.key?(:'memo')
        self.memo = attributes[:'memo']
      end

      if attributes.key?(:'originating_account_id')
        self.originating_account_id = attributes[:'originating_account_id']
      else
        self.originating_account_id = nil
      end

      if attributes.key?(:'receiving_account_id')
        self.receiving_account_id = attributes[:'receiving_account_id']
      else
        self.receiving_account_id = nil
      end

      if attributes.key?(:'reference_info')
        self.reference_info = attributes[:'reference_info']
      end

      if attributes.key?(:'risk')
        self.risk = attributes[:'risk']
      end

      if attributes.key?(:'sec_code')
        self.sec_code = attributes[:'sec_code']
      else
        self.sec_code = 'WEB'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @amount > 9999999999
        invalid_properties.push('invalid value for "amount", must be smaller than or equal to 9999999999.')
      end

      if @amount < 1
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 1.')
      end

      if !@company_entry_description.nil? && @company_entry_description.to_s.length > 10
        invalid_properties.push('invalid value for "company_entry_description", the character length must be smaller than or equal to 10.')
      end

      if !@company_name.nil? && @company_name.to_s.length > 16
        invalid_properties.push('invalid value for "company_name", the character length must be smaller than or equal to 16.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @customer_id.nil?
        invalid_properties.push('invalid value for "customer_id", customer_id cannot be nil.')
      end

      if @dc_sign.nil?
        invalid_properties.push('invalid value for "dc_sign", dc_sign cannot be nil.')
      end

      if @originating_account_id.nil?
        invalid_properties.push('invalid value for "originating_account_id", originating_account_id cannot be nil.')
      end

      if @receiving_account_id.nil?
        invalid_properties.push('invalid value for "receiving_account_id", receiving_account_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @amount.nil?
      return false if @amount > 9999999999
      return false if @amount < 1
      return false if !@company_entry_description.nil? && @company_entry_description.to_s.length > 10
      return false if !@company_name.nil? && @company_name.to_s.length > 16
      return false if @currency.nil?
      return false if @customer_id.nil?
      return false if @dc_sign.nil?
      dc_sign_validator = EnumAttributeValidator.new('String', ["credit", "debit"])
      return false unless dc_sign_validator.valid?(@dc_sign)
      return false if @originating_account_id.nil?
      return false if @receiving_account_id.nil?
      sec_code_validator = EnumAttributeValidator.new('String', ["CCD", "PPD", "WEB"])
      return false unless sec_code_validator.valid?(@sec_code)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount > 9999999999
        fail ArgumentError, 'invalid value for "amount", must be smaller than or equal to 9999999999.'
      end

      if amount < 1
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 1.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] company_entry_description Value to be assigned
    def company_entry_description=(company_entry_description)
      if !company_entry_description.nil? && company_entry_description.to_s.length > 10
        fail ArgumentError, 'invalid value for "company_entry_description", the character length must be smaller than or equal to 10.'
      end

      @company_entry_description = company_entry_description
    end

    # Custom attribute writer method with validation
    # @param [Object] company_name Value to be assigned
    def company_name=(company_name)
      if company_name.nil?
        fail ArgumentError, 'company_name cannot be nil'
      end

      if company_name.to_s.length > 16
        fail ArgumentError, 'invalid value for "company_name", the character length must be smaller than or equal to 16.'
      end

      @company_name = company_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] dc_sign Object to be assigned
    def dc_sign=(dc_sign)
      validator = EnumAttributeValidator.new('String', ["credit", "debit"])
      unless validator.valid?(dc_sign)
        warn "invalid value for \"dc_sign\", must be one of #{validator.allowable_values}."
      end
      @dc_sign = dc_sign
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sec_code Object to be assigned
    def sec_code=(sec_code)
      validator = EnumAttributeValidator.new('String', ["CCD", "PPD", "WEB"])
      unless validator.valid?(sec_code)
        warn "invalid value for \"sec_code\", must be one of #{validator.allowable_values}."
      end
      @sec_code = sec_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          company_entry_description == o.company_entry_description &&
          company_name == o.company_name &&
          currency == o.currency &&
          customer_id == o.customer_id &&
          dc_sign == o.dc_sign &&
          effective_date == o.effective_date &&
          external_data == o.external_data &&
          final_customer_id == o.final_customer_id &&
          hold == o.hold &&
          is_same_day == o.is_same_day &&
          memo == o.memo &&
          originating_account_id == o.originating_account_id &&
          receiving_account_id == o.receiving_account_id &&
          reference_info == o.reference_info &&
          risk == o.risk &&
          sec_code == o.sec_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, company_entry_description, company_name, currency, customer_id, dc_sign, effective_date, external_data, final_customer_id, hold, is_same_day, memo, originating_account_id, receiving_account_id, reference_info, risk, sec_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Synctera.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
