=begin
#Synctera API

#<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 0.74.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module Synctera
  class ResponseLicense
    # Unique ID for the business. Exactly one of `business_id` or `person_id` must be set. 
    attr_accessor :business_id

    # The date and time the license resource  was created.
    attr_accessor :creation_time

    attr_accessor :customer_id

    # License record unique id
    attr_accessor :id

    # The date and time the license resource was last updated.
    attr_accessor :last_updated_time

    # Timestamp of the last time the license was verified
    attr_accessor :last_verified_time

    # The classification of the license
    attr_accessor :license_classification

    # The date on which the license will expire
    attr_accessor :license_expiration_date

    # The date on which the license was issued
    attr_accessor :license_issuance_date

    # The entity's license number
    attr_accessor :license_number

    attr_accessor :license_type

    # Free-form text describing the type of the license
    attr_accessor :license_type_description

    # The address of the entity that holds the license as reported by the verifying vendor
    attr_accessor :licensee_address

    # The name of the entity that holds the license that's reported by the verifying vendor
    attr_accessor :licensee_name

    # The name of the licensing body that granted the license
    attr_accessor :licensing_authority

    # The status of the license
    attr_accessor :status

    # The id of the tenant containing the resource. This is relevant for Fintechs that have multiple workspaces. 
    attr_accessor :tenant

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'business_id' => :'business_id',
        :'creation_time' => :'creation_time',
        :'customer_id' => :'customer_id',
        :'id' => :'id',
        :'last_updated_time' => :'last_updated_time',
        :'last_verified_time' => :'last_verified_time',
        :'license_classification' => :'license_classification',
        :'license_expiration_date' => :'license_expiration_date',
        :'license_issuance_date' => :'license_issuance_date',
        :'license_number' => :'license_number',
        :'license_type' => :'license_type',
        :'license_type_description' => :'license_type_description',
        :'licensee_address' => :'licensee_address',
        :'licensee_name' => :'licensee_name',
        :'licensing_authority' => :'licensing_authority',
        :'status' => :'status',
        :'tenant' => :'tenant'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'business_id' => :'String',
        :'creation_time' => :'Time',
        :'customer_id' => :'String',
        :'id' => :'String',
        :'last_updated_time' => :'Time',
        :'last_verified_time' => :'Time',
        :'license_classification' => :'String',
        :'license_expiration_date' => :'Date',
        :'license_issuance_date' => :'Date',
        :'license_number' => :'String',
        :'license_type' => :'LicenseType',
        :'license_type_description' => :'String',
        :'licensee_address' => :'String',
        :'licensee_name' => :'String',
        :'licensing_authority' => :'String',
        :'status' => :'String',
        :'tenant' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Synctera::ResponseLicense` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Synctera::ResponseLicense`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      end

      if attributes.key?(:'creation_time')
        self.creation_time = attributes[:'creation_time']
      else
        self.creation_time = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'last_updated_time')
        self.last_updated_time = attributes[:'last_updated_time']
      else
        self.last_updated_time = nil
      end

      if attributes.key?(:'last_verified_time')
        self.last_verified_time = attributes[:'last_verified_time']
      end

      if attributes.key?(:'license_classification')
        self.license_classification = attributes[:'license_classification']
      end

      if attributes.key?(:'license_expiration_date')
        self.license_expiration_date = attributes[:'license_expiration_date']
      end

      if attributes.key?(:'license_issuance_date')
        self.license_issuance_date = attributes[:'license_issuance_date']
      end

      if attributes.key?(:'license_number')
        self.license_number = attributes[:'license_number']
      else
        self.license_number = nil
      end

      if attributes.key?(:'license_type')
        self.license_type = attributes[:'license_type']
      else
        self.license_type = nil
      end

      if attributes.key?(:'license_type_description')
        self.license_type_description = attributes[:'license_type_description']
      end

      if attributes.key?(:'licensee_address')
        self.licensee_address = attributes[:'licensee_address']
      end

      if attributes.key?(:'licensee_name')
        self.licensee_name = attributes[:'licensee_name']
      end

      if attributes.key?(:'licensing_authority')
        self.licensing_authority = attributes[:'licensing_authority']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'tenant')
        self.tenant = attributes[:'tenant']
      else
        self.tenant = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @creation_time.nil?
        invalid_properties.push('invalid value for "creation_time", creation_time cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @last_updated_time.nil?
        invalid_properties.push('invalid value for "last_updated_time", last_updated_time cannot be nil.')
      end

      if @license_number.nil?
        invalid_properties.push('invalid value for "license_number", license_number cannot be nil.')
      end

      if @license_number.to_s.length < 1
        invalid_properties.push('invalid value for "license_number", the character length must be great than or equal to 1.')
      end

      if @license_type.nil?
        invalid_properties.push('invalid value for "license_type", license_type cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @tenant.nil?
        invalid_properties.push('invalid value for "tenant", tenant cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @creation_time.nil?
      return false if @id.nil?
      return false if @last_updated_time.nil?
      license_classification_validator = EnumAttributeValidator.new('String', ["MEDICAL_AND_RECREATIONAL_CANNABIS", "MEDICAL_CANNABIS", "RECREATIONAL_CANNABIS"])
      return false unless license_classification_validator.valid?(@license_classification)
      return false if @license_number.nil?
      return false if @license_number.to_s.length < 1
      return false if @license_type.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["ACCEPTED", "REJECTED", "REVIEW", "UNVERIFIED"])
      return false unless status_validator.valid?(@status)
      return false if @tenant.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] license_classification Object to be assigned
    def license_classification=(license_classification)
      validator = EnumAttributeValidator.new('String', ["MEDICAL_AND_RECREATIONAL_CANNABIS", "MEDICAL_CANNABIS", "RECREATIONAL_CANNABIS"])
      unless validator.valid?(license_classification)
        fail ArgumentError, "invalid value for \"license_classification\", must be one of #{validator.allowable_values}."
      end
      @license_classification = license_classification
    end

    # Custom attribute writer method with validation
    # @param [Object] license_number Value to be assigned
    def license_number=(license_number)
      if license_number.nil?
        fail ArgumentError, 'license_number cannot be nil'
      end

      if license_number.to_s.length < 1
        fail ArgumentError, 'invalid value for "license_number", the character length must be great than or equal to 1.'
      end

      @license_number = license_number
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ACCEPTED", "REJECTED", "REVIEW", "UNVERIFIED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          business_id == o.business_id &&
          creation_time == o.creation_time &&
          customer_id == o.customer_id &&
          id == o.id &&
          last_updated_time == o.last_updated_time &&
          last_verified_time == o.last_verified_time &&
          license_classification == o.license_classification &&
          license_expiration_date == o.license_expiration_date &&
          license_issuance_date == o.license_issuance_date &&
          license_number == o.license_number &&
          license_type == o.license_type &&
          license_type_description == o.license_type_description &&
          licensee_address == o.licensee_address &&
          licensee_name == o.licensee_name &&
          licensing_authority == o.licensing_authority &&
          status == o.status &&
          tenant == o.tenant
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [business_id, creation_time, customer_id, id, last_updated_time, last_verified_time, license_classification, license_expiration_date, license_issuance_date, license_number, license_type, license_type_description, licensee_address, licensee_name, licensing_authority, status, tenant].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Synctera.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
