=begin
#Synctera API

#This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

The version of the OpenAPI document: 1.82.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module Synctera
  class WireTransactionSubtypes
    DOMESTIC_INCOMING = "DOMESTIC_INCOMING".freeze
    DOMESTIC_INCOMING_RETURN = "DOMESTIC_INCOMING_RETURN".freeze
    DOMESTIC_INCOMING_RETURN_REVERSAL = "DOMESTIC_INCOMING_RETURN_REVERSAL".freeze
    DOMESTIC_INCOMING_REVERSAL = "DOMESTIC_INCOMING_REVERSAL".freeze
    DOMESTIC_OUTGOING = "DOMESTIC_OUTGOING".freeze
    DOMESTIC_OUTGOING_RETURN = "DOMESTIC_OUTGOING_RETURN".freeze
    DOMESTIC_OUTGOING_RETURN_REVERSAL = "DOMESTIC_OUTGOING_RETURN_REVERSAL".freeze
    DOMESTIC_OUTGOING_REVERSAL = "DOMESTIC_OUTGOING_REVERSAL".freeze
    INTERNATIONAL_OUTGOING = "INTERNATIONAL_OUTGOING".freeze
    INTERNATIONAL_OUTGOING_REVERSAL = "INTERNATIONAL_OUTGOING_REVERSAL".freeze

    def self.all_vars
      @all_vars ||= [DOMESTIC_INCOMING, DOMESTIC_INCOMING_RETURN, DOMESTIC_INCOMING_RETURN_REVERSAL, DOMESTIC_INCOMING_REVERSAL, DOMESTIC_OUTGOING, DOMESTIC_OUTGOING_RETURN, DOMESTIC_OUTGOING_RETURN_REVERSAL, DOMESTIC_OUTGOING_REVERSAL, INTERNATIONAL_OUTGOING, INTERNATIONAL_OUTGOING_REVERSAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WireTransactionSubtypes.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WireTransactionSubtypes"
    end
  end
end
